import { Prisma, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const gradeLabels: Prisma.GradeLabelCreateManyInput[] = [
  {
    gradeLabelId: 1,
    gpaStatusName: 'blue',
    gpaMinInStatus: 3.25,
    gpaStatusMax: 4,
    gpaxStatusName: 'เกียรตินิยม',
    gpaxStatusMin: 3.25,
    gpaxStatusMax: 4,
  },
  {
    gradeLabelId: 2,
    gpaStatusName: 'green',
    gpaMinInStatus: 2,
    gpaStatusMax: 3.2499,
    gpaxStatusName: 'ปกติ',
    gpaxStatusMin: 1.76,
    gpaxStatusMax: 3.24,
  },
  {
    gradeLabelId: 3,
    gpaStatusName: 'orange',
    gpaMinInStatus: 1.75,
    gpaStatusMax: 1.9999,
    gpaxStatusName: 'รอพินิจ',
    gpaxStatusMin: 1.51,
    gpaxStatusMax: 1.75,
  },
  {
    gradeLabelId: 4,
    gpaStatusName: 'red',
    gpaMinInStatus: 0,
    gpaStatusMax: 1.7499,
    gpaxStatusName: 'โปรต่ำ',
    gpaxStatusMin: 0,
    gpaxStatusMax: 1.5,
  },
];

const subjectCategories: Prisma.SubjectCaterogyCreateManyInput[] = [
  {
    subjectCaterogyId: 1,
    subjectCategoryName: 'หมวดวิชาศึกษาทั่วไป',
    subjectGroupName: 'กลุ่มสาระอยู่ดีมีสุข',
  },
  {
    subjectCaterogyId: 2,
    subjectCategoryName: 'หมวดวิชาศึกษาทั่วไป',
    subjectGroupName: 'กลุ่มสาระศาสตร์แห่งผู้ประกอบการ',
  },
  {
    subjectCaterogyId: 3,
    subjectCategoryName: 'หมวดวิชาศึกษาทั่วไป',
    subjectGroupName: 'กลุ่มสาระภาษากับการสื่อสาร',
  },
  {
    subjectCaterogyId: 4,
    subjectCategoryName: 'หมวดวิชาศึกษาทั่วไป',
    subjectGroupName: 'กลุ่มสาระพลเมืองไทยและพลเมืองโลก',
  },
  {
    subjectCaterogyId: 5,
    subjectCategoryName: 'หมวดวิชาศึกษาทั่วไป',
    subjectGroupName: 'กลุ่มสาระสุนทรียศาสตร์',
  },
  {
    subjectCaterogyId: 6,
    subjectCategoryName: 'หมวดวิชาเลือกเสรี',
    subjectGroupName: 'วิชาเลือกเสรี',
  },
  {
    subjectCaterogyId: 7,
    subjectCategoryName: 'หมวดวิชาเฉพาะ',
    subjectGroupName: 'วิชาเลือก',
  },
  {
    subjectCaterogyId: 8,
    subjectCategoryName: 'หมวดวิชาเฉพาะ',
    subjectGroupName: 'วิชาแกน',
  },
  {
    subjectCaterogyId: 9,
    subjectCategoryName: 'หมวดวิชาเฉพาะ',
    subjectGroupName: 'วิชาเฉพาะด้าน',
  },
];

const courses: Prisma.CourseCreateManyInput[] = [
  {
    courseId: 1,
    nameCourseTh: 'หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมคอมพิวเตอร์',
    nameCourseUse: 'วศ.คอม 65',
  },
  {
    courseId: 2,
    nameCourseTh: 'หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมโยธา',
    nameCourseUse: 'วศ.โยธา 65',
  },
];

const coursePlans: Prisma.CoursePlanCreateManyInput[] = [
  {
    coursePlanId: 1,
    courseId: 1,
    planCourse: 'แผนสหกิจศึกษา',
    creditIntern: 128,
    totalCredit: 134,
    couseStartYear: 2565,
    couseEndYear: 2570,
    generalSubjectCredit: 30,
    specificSubjectCredit: 98,
    freeSubjectCredit: 6,
    coreSubjectCredit: 30,
    spacailSubjectCredit: 49,
    selectSubjectCredit: 19,
    happySubjectCredit: 3,
    entrepreneurshipSubjectCredit: 6,
    languageSubjectCredit: 13,
    peopleSubjectCredit: 5,
    aestheticsSubjectCredit: 3,
    internshipHours: 240,
  },
  {
    coursePlanId: 2,
    courseId: 1,
    planCourse: 'แผนไม่สหกิจศึกษา',
    creditIntern: 128,
    totalCredit: 134,
    couseStartYear: 2565,
    couseEndYear: 2570,
    generalSubjectCredit: 30,
    specificSubjectCredit: 98,
    freeSubjectCredit: 6,
    coreSubjectCredit: 30,
    spacailSubjectCredit: 49,
    selectSubjectCredit: 19,
    happySubjectCredit: 3,
    entrepreneurshipSubjectCredit: 6,
    languageSubjectCredit: 13,
    peopleSubjectCredit: 5,
    aestheticsSubjectCredit: 3,
    internshipHours: null,
  },
];

const subjects: Prisma.SubjectCreateManyInput[] = [
  {
    subjectId: 1,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '02204171',
    subjectCourse: 65,
    nameSubjectThai: 'การเขียนโปรแกรมเชิงโครงสร้าง',
    nameSubjectEng: 'Programing Structur',
    credit: 3,
  },
  {
    subjectId: 2,
    courseId: 1,
    subjectCaterogyId: 3,
    subjectCreditId: 1,
    subjectCode: '1355101',
    subjectCourse: 65,
    nameSubjectThai: 'ภาษาอังกฤษในชีวิตประจำวัน',
    nameSubjectEng: 'Eng I',
    credit: 3,
  },
  {
    subjectId: 3,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01417167',
    subjectCourse: 65,
    nameSubjectThai: 'คณิตศาสตร์วิศวกรรม I',
    nameSubjectEng: 'Math I',
    credit: 3,
  },
  {
    subjectId: 4,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01420111',
    subjectCourse: 65,
    nameSubjectThai: 'ฟิสิกส์ทั่วไป I',
    nameSubjectEng: 'Physic I',
    credit: 3,
  },
  {
    subjectId: 5,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01420113',
    subjectCourse: 65,
    nameSubjectThai: 'ปฎิบัติการฟิสิกส์ I',
    nameSubjectEng: 'Lab Physic I',
    credit: 1,
  },
  {
    subjectId: 6,
    courseId: 1,
    subjectCaterogyId: 3,
    subjectCreditId: 1,
    subjectCode: '1999021',
    subjectCourse: 65,
    nameSubjectThai: 'ภาษาไทยเพื่อการสื่อสาร',
    nameSubjectEng: 'Thai Languages',
    credit: 3,
  },
  {
    subjectId: 7,
    courseId: 1,
    subjectCaterogyId: 4,
    subjectCreditId: 1,
    subjectCode: '01999111',
    subjectCourse: 65,
    nameSubjectThai: 'ศาสตร์แห่งแผ่นดิน',
    nameSubjectEng: 'Knowledge of the Land',
    credit: 2,
  },
  {
    subjectId: 8,
    courseId: 1,
    subjectCaterogyId: 5,
    subjectCreditId: 1,
    subjectCode: '02708102',
    subjectCourse: 65,
    nameSubjectThai: 'วรรณกรรมกับวิทยาศาสตร์',
    nameSubjectEng: 'Literature and Science',
    credit: 3,
  },
  {
    subjectId: 9,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204172',
    subjectCourse: 65,
    nameSubjectThai: 'การฝึกภาคปฏิบัติทางวิศวกรรมคอมพิวเตอร์',
    nameSubjectEng: 'Practicum in Computer Engineering',
    credit: 1,
  },
  {
    subjectId: 10,
    courseId: 1,
    subjectCaterogyId: 1,
    subjectCreditId: 1,
    subjectCode: '01174231',
    subjectCourse: 65,
    nameSubjectThai: 'นันทนาการเบื้องต้น',
    nameSubjectEng: 'Introduction to Recreation',
    credit: 2,
  },
  {
    subjectId: 11,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204111',
    subjectCourse: 65,
    nameSubjectThai: 'วิยุตคณิต',
    nameSubjectEng: 'Discrete Mathematics',
    credit: 3,
  },
  {
    subjectId: 12,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01420114',
    subjectCourse: 65,
    nameSubjectThai: 'ปฏิบัติการฟิสิกส์ II',
    nameSubjectEng: 'Laboratory in Physics II',
    credit: 1,
  },
  {
    subjectId: 13,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01420112',
    subjectCourse: 65,
    nameSubjectThai: 'ฟิสิกส์ทั่วไป II',
    nameSubjectEng: 'General Physics II',
    credit: 3,
  },
  {
    subjectId: 14,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01417168',
    subjectCourse: 65,
    nameSubjectThai: 'คณิตศาสตร์วิศวกรรม II',
    nameSubjectEng: 'Engineering Mathematics II',
    credit: 3,
  },
  {
    subjectId: 15,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204121',
    subjectCourse: 65,
    nameSubjectThai: 'หลักมูลดิจิทัล',
    nameSubjectEng: 'Digital Fundamentals',
    credit: 3,
  },
  {
    subjectId: 16,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01403117',
    subjectCourse: 65,
    nameSubjectThai: 'หลักมูลเคมีทั่วไป',
    nameSubjectEng: 'Fundamentals of General Chemistry',
    credit: 3,
  },
  {
    subjectId: 17,
    courseId: 1,
    subjectCaterogyId: 1,
    subjectCreditId: 1,
    subjectCode: '01175113',
    subjectCourse: 65,
    nameSubjectThai: 'เทนนิสเพื่อสุขภาพ',
    nameSubjectEng: 'Tennis for Health',
    credit: 1,
  },
  {
    subjectId: 18,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01417267',
    subjectCourse: 65,
    nameSubjectThai: 'คณิตศาสตร์วิศวกรรม III',
    nameSubjectEng: 'Engineering Mathematics III',
    credit: 3,
  },
  {
    subjectId: 19,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '02204221',
    subjectCourse: 65,
    nameSubjectThai: 'วิศวกรรมไฟฟ้าสำหรับวิศวกรคอมพิวเตอร์',
    nameSubjectEng: 'Electrical Engineering for Computer Engineers',
    credit: 3,
  },
  {
    subjectId: 20,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204271',
    subjectCourse: 65,
    nameSubjectThai: 'การเขียนโปรแกรมเชิงวัตถุ',
    nameSubjectEng: 'Object-Oriented Programming',
    credit: 3,
  },
  {
    subjectId: 21,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01403114',
    subjectCourse: 65,
    nameSubjectThai: 'ปฏิบัติการหลักมูลเคมีทั่วไป',
    nameSubjectEng: 'Laboratory in Fundamentals of General Chemistry',
    credit: 1,
  },
  {
    subjectId: 22,
    courseId: 1,
    subjectCaterogyId: 3,
    subjectCreditId: 1,
    subjectCode: '01355102',
    subjectCourse: 65,
    nameSubjectThai: 'ภาษาอังกฤษในมหาวิทยาลัย',
    nameSubjectEng: 'English for University Life',
    credit: 3,
  },
  {
    subjectId: 23,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204231',
    subjectCourse: 65,
    nameSubjectThai: 'โครงสร้างข้อมูลและขั้นตอนวิธี I',
    nameSubjectEng: 'Data Structures and Algorithms I',
    credit: 3,
  },
  {
    subjectId: 24,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204241',
    subjectCourse: 65,
    nameSubjectThai: 'สถาปัตยกรรมคอมพิวเตอร์',
    nameSubjectEng: 'Computer Architecture',
    credit: 3,
  },
  {
    subjectId: 25,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204223',
    subjectCourse: 65,
    nameSubjectThai: 'หลักมูลอิเล็กทรอนิกส์',
    nameSubjectEng: 'Electronics Fundamentals',
    credit: 3,
  },
  {
    subjectId: 26,
    courseId: 1,
    subjectCaterogyId: 2,
    subjectCreditId: 1,
    subjectCode: '02714101',
    subjectCourse: 65,
    nameSubjectThai: 'การคิดเชิงวิพากษ์และการแก้ปัญหา',
    nameSubjectEng: 'Critical Thinking and Problem Solving',
    credit: 3,
  },
  {
    subjectId: 27,
    courseId: 1,
    subjectCaterogyId: 8,
    subjectCreditId: 1,
    subjectCode: '01208111',
    subjectCourse: 65,
    nameSubjectThai: 'การเขียนแบบวิศวกรรม',
    nameSubjectEng: 'Engineering Drawing',
    credit: 3,
  },
  {
    subjectId: 28,
    courseId: 1,
    subjectCaterogyId: 3,
    subjectCreditId: 1,
    subjectCode: '01371111',
    subjectCourse: 65,
    nameSubjectThai: 'สื่อสารสนเทศเพื่อการเรียนรู้',
    nameSubjectEng: 'Information Media for Learning',
    credit: 1,
  },
  {
    subjectId: 29,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204281',
    subjectCourse: 65,
    nameSubjectThai: 'การสื่อสารข้อมูลและระบบเครือข่าย คอมพิวเตอร์',
    nameSubjectEng: 'Data Communications and Computer Network Systems',
    credit: 3,
  },
  {
    subjectId: 30,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204232',
    subjectCourse: 65,
    nameSubjectThai: 'โครงสร้างข้อมูลและขั้นตอนวิธี II',
    nameSubjectEng: 'Data Structures and Algorithms II',
    credit: 3,
  },
  {
    subjectId: 31,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204361',
    subjectCourse: 65,
    nameSubjectThai: 'การจัดการระบบฐานข้อมูล',
    nameSubjectEng: 'Database Systems Management',
    credit: 3,
  },
  {
    subjectId: 32,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204331',
    subjectCourse: 65,
    nameSubjectThai: 'ปัญญาประดิษฐ์สำหรับวิศวกรคอมพิวเตอร์',
    nameSubjectEng: 'Artificial Intelligence for Computer Engineers',
    credit: 3,
  },
  {
    subjectId: 33,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204321',
    subjectCourse: 65,
    nameSubjectThai: 'สัญญาณและระบบ',
    nameSubjectEng: 'Signals and Systems',
    credit: 3,
  },
  {
    subjectId: 34,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204311',
    subjectCourse: 65,
    nameSubjectThai: 'ความน่าจะเป็นและสถิติสำหรับวิศวกร คอมพิวเตอร์',
    nameSubjectEng: 'Probability and Statistics for Computer Engineers',
    credit: 3,
  },
  {
    subjectId: 35,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204351',
    subjectCourse: 65,
    nameSubjectThai: 'วิศวกรรมระบบปฏิบัติการ',
    nameSubjectEng: 'Operating Systems Engineering',
    credit: 3,
  },
  {
    subjectId: 36,
    courseId: 1,
    subjectCaterogyId: 3,
    subjectCreditId: 1,
    subjectCode: '01355103',
    subjectCourse: 65,
    nameSubjectThai: 'ภาษาอังกฤษเพื่อโอกาสในการทำงาน',
    nameSubjectEng: 'English for Job Opportunities',
    credit: 3,
  },
  {
    subjectId: 37,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204352',
    subjectCourse: 65,
    nameSubjectThai: 'ความปลอดภัยทางไซเบอร์และระบบ',
    nameSubjectEng: 'Cyber and Systems Security',
    credit: 3,
  },
  {
    subjectId: 38,
    courseId: 1,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204472',
    subjectCourse: 65,
    nameSubjectThai: 'การพัฒนาโมบายแอพลิเคชัน',
    nameSubjectEng: 'Mobile Application Development',
    credit: 3,
  },
  {
    subjectId: 39,
    courseId: 1,
    subjectCaterogyId: 5,
    subjectCreditId: 1,
    subjectCode: '01999141',
    subjectCourse: 65,
    nameSubjectThai: 'มนุษย์กับสังคม',
    nameSubjectEng: 'Man and Society',
    credit: 3,
  },
  {
    subjectId: 40,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204341',
    subjectCourse: 65,
    nameSubjectThai: 'ระบบฝังตัว',
    nameSubjectEng: 'Embedded System',
    credit: 3,
  },
  {
    subjectId: 41,
    courseId: 1,
    subjectCaterogyId: 9,
    subjectCreditId: 1,
    subjectCode: '02204371',
    subjectCourse: 65,
    nameSubjectThai: 'วิศวกรรมซอฟต์แวร์',
    nameSubjectEng: 'Software Engineering',
    credit: 3,
  },
  {
    subjectId: 42,
    courseId: 1,
    subjectCaterogyId: 2,
    subjectCreditId: 1,
    subjectCode: '01200101',
    subjectCourse: 65,
    nameSubjectThai: 'การคิดเชิงนวัตกรรม',
    nameSubjectEng: 'Innovative Thinking',
    credit: 3,
  },
  {
    subjectId: 43,
    courseId: 1,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204451',
    subjectCourse: 65,
    nameSubjectThai: 'สถาปัตยกรรมเชิงบริการ',
    nameSubjectEng: 'Service Oriented Architectures',
    credit: 3,
  },
  {
    subjectId: 44,
    courseId: 1,
    subjectCaterogyId: 6,
    subjectCreditId: 1,
    subjectCode: '03751111',
    subjectCourse: 65,
    nameSubjectThai: 'มนุษย์กับสิ่งแวดล้อม',
    nameSubjectEng: 'Man and Environment',
    credit: 3,
  },
  {
    subjectId: 45,
    courseId: 1,
    subjectCaterogyId: 6,
    subjectCreditId: 1,
    subjectCode: '02738453',
    subjectCourse: 65,
    nameSubjectThai: 'เศรษฐกิจบีซีจี',
    nameSubjectEng: 'BCG Economy',
    credit: 3,
  },
  {
    subjectId: 46,
    courseId: 1,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204471',
    subjectCourse: 65,
    nameSubjectThai: 'การพัฒนาเว็บแอพลิเคชัน',
    nameSubjectEng: 'Web Application Development',
    credit: 3,
  },
  {
    subjectId: 47,
    courseId: 1,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204462',
    subjectCourse: 65,
    nameSubjectThai: 'คลังข้อมูลและระบบธุรกิจอัจฉริยะ',
    nameSubjectEng: 'Data Warehouse and Business Intelligence System',
    credit: 3,
  },
  {
    subjectId: 48,
    courseId: 1,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204390',
    subjectCourse: 65,
    nameSubjectThai: 'การเตรียมความพร้อมสหกิจศึกษา',
    nameSubjectEng: 'Cooperative Education Preparation',
    credit: 1,
  },
  {
    subjectId: 49,
    courseId: 1,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204490',
    subjectCourse: 65,
    nameSubjectThai: 'สหกิจศึกษา',
    nameSubjectEng: 'Cooperative Education',
    credit: 6,
  },
  {
    subjectId: 50,
    courseId: 2,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204495',
    subjectCourse: 65,
    nameSubjectThai: 'โปรเจค I',
    nameSubjectEng: 'Computer Project I',
    credit: 2,
  },
  {
    subjectId: 51,
    courseId: 2,
    subjectCaterogyId: 7,
    subjectCreditId: 1,
    subjectCode: '02204499',
    subjectCourse: 65,
    nameSubjectThai: 'โปรเจค II',
    nameSubjectEng: 'Computer Project II',
    credit: 2,
  },
];

const subjectCourses: Prisma.SubjectCourseCreateManyInput[] = [
  { subjectCourseId: 1, subjectId: 1, coursePlanId: 1, studyYear: 1, term: 1 },
  { subjectCourseId: 2, subjectId: 2, coursePlanId: 1, studyYear: 1, term: 1 },
  { subjectCourseId: 3, subjectId: 3, coursePlanId: 1, studyYear: 1, term: 1 },
  { subjectCourseId: 4, subjectId: 4, coursePlanId: 1, studyYear: 1, term: 1 },
  { subjectCourseId: 5, subjectId: 5, coursePlanId: 1, studyYear: 1, term: 1 },
  { subjectCourseId: 6, subjectId: 6, coursePlanId: 1, studyYear: 1, term: 1 },
  { subjectCourseId: 7, subjectId: 7, coursePlanId: 1, studyYear: 1, term: 1 },
  { subjectCourseId: 8, subjectId: 8, coursePlanId: 1, studyYear: 1, term: 2 },
  { subjectCourseId: 9, subjectId: 9, coursePlanId: 1, studyYear: 1, term: 2 },
  {
    subjectCourseId: 10,
    subjectId: 10,
    coursePlanId: 1,
    studyYear: 1,
    term: 2,
  },
  {
    subjectCourseId: 11,
    subjectId: 11,
    coursePlanId: 1,
    studyYear: 1,
    term: 2,
  },
  {
    subjectCourseId: 12,
    subjectId: 12,
    coursePlanId: 1,
    studyYear: 1,
    term: 2,
  },
  {
    subjectCourseId: 13,
    subjectId: 13,
    coursePlanId: 1,
    studyYear: 1,
    term: 2,
  },
  {
    subjectCourseId: 14,
    subjectId: 14,
    coursePlanId: 1,
    studyYear: 1,
    term: 2,
  },
  {
    subjectCourseId: 15,
    subjectId: 15,
    coursePlanId: 1,
    studyYear: 1,
    term: 2,
  },
  {
    subjectCourseId: 16,
    subjectId: 16,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 17,
    subjectId: 17,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 18,
    subjectId: 18,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 19,
    subjectId: 19,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 20,
    subjectId: 20,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 21,
    subjectId: 21,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 22,
    subjectId: 22,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 23,
    subjectId: 23,
    coursePlanId: 1,
    studyYear: 2,
    term: 1,
  },
  {
    subjectCourseId: 24,
    subjectId: 24,
    coursePlanId: 1,
    studyYear: 2,
    term: 2,
  },
  {
    subjectCourseId: 25,
    subjectId: 25,
    coursePlanId: 1,
    studyYear: 2,
    term: 2,
  },
  {
    subjectCourseId: 26,
    subjectId: 26,
    coursePlanId: 1,
    studyYear: 2,
    term: 2,
  },
  {
    subjectCourseId: 27,
    subjectId: 27,
    coursePlanId: 1,
    studyYear: 2,
    term: 2,
  },
  {
    subjectCourseId: 28,
    subjectId: 28,
    coursePlanId: 1,
    studyYear: 2,
    term: 2,
  },
  {
    subjectCourseId: 29,
    subjectId: 29,
    coursePlanId: 1,
    studyYear: 2,
    term: 2,
  },
  {
    subjectCourseId: 30,
    subjectId: 30,
    coursePlanId: 1,
    studyYear: 2,
    term: 2,
  },
  {
    subjectCourseId: 31,
    subjectId: 31,
    coursePlanId: 1,
    studyYear: 3,
    term: 1,
  },
  {
    subjectCourseId: 32,
    subjectId: 32,
    coursePlanId: 1,
    studyYear: 3,
    term: 1,
  },
  {
    subjectCourseId: 33,
    subjectId: 33,
    coursePlanId: 1,
    studyYear: 3,
    term: 1,
  },
  {
    subjectCourseId: 34,
    subjectId: 34,
    coursePlanId: 1,
    studyYear: 3,
    term: 1,
  },
  {
    subjectCourseId: 35,
    subjectId: 35,
    coursePlanId: 1,
    studyYear: 3,
    term: 1,
  },
  {
    subjectCourseId: 36,
    subjectId: 36,
    coursePlanId: 1,
    studyYear: 3,
    term: 1,
  },
  {
    subjectCourseId: 37,
    subjectId: 37,
    coursePlanId: 1,
    studyYear: 3,
    term: 2,
  },
  {
    subjectCourseId: 38,
    subjectId: 38,
    coursePlanId: 1,
    studyYear: 3,
    term: 2,
  },
  {
    subjectCourseId: 39,
    subjectId: 39,
    coursePlanId: 1,
    studyYear: 3,
    term: 2,
  },
  {
    subjectCourseId: 40,
    subjectId: 40,
    coursePlanId: 1,
    studyYear: 3,
    term: 2,
  },
  {
    subjectCourseId: 41,
    subjectId: 41,
    coursePlanId: 1,
    studyYear: 3,
    term: 2,
  },
  {
    subjectCourseId: 42,
    subjectId: 42,
    coursePlanId: 1,
    studyYear: 3,
    term: 2,
  },
  {
    subjectCourseId: 43,
    subjectId: 43,
    coursePlanId: 1,
    studyYear: 3,
    term: 2,
  },
  {
    subjectCourseId: 44,
    subjectId: 44,
    coursePlanId: 1,
    studyYear: 4,
    term: 1,
  },
  {
    subjectCourseId: 45,
    subjectId: 45,
    coursePlanId: 1,
    studyYear: 4,
    term: 1,
  },
  {
    subjectCourseId: 46,
    subjectId: 46,
    coursePlanId: 1,
    studyYear: 4,
    term: 1,
  },
  {
    subjectCourseId: 47,
    subjectId: 47,
    coursePlanId: 1,
    studyYear: 4,
    term: 1,
  },
  {
    subjectCourseId: 48,
    subjectId: 48,
    coursePlanId: 1,
    studyYear: 4,
    term: 1,
  },
  {
    subjectCourseId: 49,
    subjectId: 49,
    coursePlanId: 1,
    studyYear: 4,
    term: 1,
  },
];

const subjectCredits: Prisma.SubjectCreditCreateManyInput[] = [
  {
    subjectCreditId: 1,
    lectureCredit: 3,
    labCredit: 0,
    lectureHours: 3,
    labHours: 2,
    bySelfHours: 6,
  },
  {
    subjectCreditId: 2,
    lectureCredit: 3,
    labCredit: 2,
    lectureHours: 3,
    labHours: 2,
    bySelfHours: 6,
  },
  {
    subjectCreditId: 3,
    lectureCredit: 0,
    labCredit: 3,
    lectureHours: 3,
    labHours: 2,
    bySelfHours: 6,
  },
  {
    subjectCreditId: 4,
    lectureCredit: 2,
    labCredit: 1,
    lectureHours: 3,
    labHours: 2,
    bySelfHours: 6,
  },
  {
    subjectCreditId: 5,
    lectureCredit: 2,
    labCredit: 3,
    lectureHours: 3,
    labHours: 2,
    bySelfHours: 6,
  },
  {
    subjectCreditId: 6,
    lectureCredit: 3,
    labCredit: 2,
    lectureHours: 3,
    labHours: 2,
    bySelfHours: 6,
  },
  {
    subjectCreditId: 7,
    lectureCredit: 3,
    labCredit: 3,
    lectureHours: 3,
    labHours: 2,
    bySelfHours: 6,
  },
];

const studentStatuses: Prisma.StudentStatusCreateManyInput[] = [
  { studentStatusId: 1, status: 'กำลังศึกษา' },
  { studentStatusId: 2, status: 'พ้นสภาพนิสิต' },
  { studentStatusId: 3, status: 'จบการศึกษา' },
];

const students: Prisma.StudentCreateManyInput[] = [
  {
    studentId: '6520501001',
    studentUsername: 'b6520501001',
    studentStatusId: 1,
    coursePlanId: 1,
  },
  {
    studentId: '6520501002',
    studentUsername: 'b6520501002',
    studentStatusId: 1,
    coursePlanId: 1,
  },
  {
    studentId: '6520501003',
    studentUsername: 'b6520501003',
    studentStatusId: 1,
    coursePlanId: 1,
  },
  {
    studentId: '6520501004',
    studentUsername: 'b6520501004',
    studentStatusId: 1,
    coursePlanId: 1,
  },
];

const creditRequires: Prisma.CreditRequireCreateManyInput[] = [
  {
    creditRequireId: 1,
    coursePlanId: 1,
    subjectCaterogyId: 1,
    creditSubject: 3,
  },
  {
    creditRequireId: 2,
    coursePlanId: 1,
    subjectCaterogyId: 2,
    creditSubject: 6,
  },
  {
    creditRequireId: 3,
    coursePlanId: 1,
    subjectCaterogyId: 3,
    creditSubject: 13,
  },
  {
    creditRequireId: 4,
    coursePlanId: 1,
    subjectCaterogyId: 4,
    creditSubject: 5,
  },
  {
    creditRequireId: 5,
    coursePlanId: 1,
    subjectCaterogyId: 5,
    creditSubject: 3,
  },
  {
    creditRequireId: 6,
    coursePlanId: 1,
    subjectCaterogyId: 6,
    creditSubject: 6,
  },
  {
    creditRequireId: 7,
    coursePlanId: 1,
    subjectCaterogyId: 7,
    creditSubject: 19,
  },
  {
    creditRequireId: 8,
    coursePlanId: 1,
    subjectCaterogyId: 8,
    creditSubject: 30,
  },
  {
    creditRequireId: 9,
    coursePlanId: 1,
    subjectCaterogyId: 9,
    creditSubject: 49,
  },
];

const factRegisters: Prisma.FactRegisterCreateManyInput[] = [
  {
    regisId: 1,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 1,
    gradeNumber: 1.5,
    gradeCharacter: 'D+',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 3,
  },
  {
    regisId: 2,
    studentId: '6520501001',
    creditRequireId: 3,
    subjectCourseId: 2,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 3,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 3,
    gradeNumber: 3.5,
    gradeCharacter: 'B+',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 4,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 4,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 2,
  },
  {
    regisId: 5,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 5,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 1,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 6,
    studentId: '6520501001',
    creditRequireId: 3,
    subjectCourseId: 6,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 7,
    studentId: '6520501001',
    creditRequireId: 4,
    subjectCourseId: 7,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 2,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 8,
    studentId: '6520501001',
    creditRequireId: 5,
    subjectCourseId: 8,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 9,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 9,
    gradeNumber: 2.5,
    gradeCharacter: 'C+',
    creditRegis: 1,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 3,
  },
  {
    regisId: 10,
    studentId: '6520501001',
    creditRequireId: 1,
    subjectCourseId: 10,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 2,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 11,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 11,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 12,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 12,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 1,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 13,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 13,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 14,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 14,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 15,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 15,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 2,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 16,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 16,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 17,
    studentId: '6520501001',
    creditRequireId: 1,
    subjectCourseId: 17,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 1,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 18,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 18,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 2,
  },
  {
    regisId: 19,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 19,
    gradeNumber: 3.5,
    gradeCharacter: 'B+',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 20,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 20,
    gradeNumber: 2,
    gradeCharacter: 'C',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 3,
  },
  {
    regisId: 21,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 21,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 1,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 22,
    studentId: '6520501001',
    creditRequireId: 3,
    subjectCourseId: 22,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 23,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 23,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 4,
    studyYearInRegis: 2,
    studyTermInRegis: 1,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 2,
  },
  {
    regisId: 24,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 24,
    gradeNumber: 3.5,
    gradeCharacter: 'B+',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 2,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 25,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 25,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 2,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 26,
    studentId: '6520501001',
    creditRequireId: 2,
    subjectCourseId: 26,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 2,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 27,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 27,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 2,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 28,
    studentId: '6520501001',
    creditRequireId: 3,
    subjectCourseId: 28,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 1,
    studyYearInRegis: 2,
    studyTermInRegis: 2,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 29,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 29,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 2,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 30,
    studentId: '6520501001',
    creditRequireId: 8,
    subjectCourseId: 30,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 2,
    studyTermInRegis: 2,
    semesterYearInRegis: 2566,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 31,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 31,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 1,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 2,
  },
  {
    regisId: 32,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 32,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 1,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 33,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 33,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 1,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 34,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 34,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 1,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 35,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 35,
    gradeNumber: 3.5,
    gradeCharacter: 'B+',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 1,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 36,
    studentId: '6520501001',
    creditRequireId: 3,
    subjectCourseId: 36,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 1,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: 1,
  },
  {
    regisId: 37,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 37,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 2,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 38,
    studentId: '6520501001',
    creditRequireId: 7,
    subjectCourseId: 38,
    gradeNumber: 2,
    gradeCharacter: 'C',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 2,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 3,
  },
  {
    regisId: 39,
    studentId: '6520501001',
    creditRequireId: 5,
    subjectCourseId: 39,
    gradeNumber: 3.5,
    gradeCharacter: 'B+',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 2,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 40,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 40,
    gradeNumber: 3.5,
    gradeCharacter: 'B+',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 2,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 41,
    studentId: '6520501001',
    creditRequireId: 9,
    subjectCourseId: 41,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 2,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 42,
    studentId: '6520501001',
    creditRequireId: 2,
    subjectCourseId: 42,
    gradeNumber: 4,
    gradeCharacter: 'A',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 2,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 1,
  },
  {
    regisId: 43,
    studentId: '6520501001',
    creditRequireId: 7,
    subjectCourseId: 43,
    gradeNumber: 3,
    gradeCharacter: 'B',
    creditRegis: 3,
    studyYearInRegis: 3,
    studyTermInRegis: 2,
    semesterYearInRegis: 2567,
    semesterPartInRegis: 'ภาคปลาย',
    gradeLabelId: 2,
  },
  {
    regisId: 44,
    studentId: '6520501001',
    creditRequireId: 6,
    subjectCourseId: 44,
    gradeNumber: null,
    gradeCharacter: null,
    creditRegis: 3,
    studyYearInRegis: 4,
    studyTermInRegis: 1,
    semesterYearInRegis: 2568,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    regisId: 45,
    studentId: '6520501001',
    creditRequireId: 6,
    subjectCourseId: 45,
    gradeNumber: null,
    gradeCharacter: null,
    creditRegis: 3,
    studyYearInRegis: 4,
    studyTermInRegis: 1,
    semesterYearInRegis: 2568,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    regisId: 46,
    studentId: '6520501001',
    creditRequireId: 7,
    subjectCourseId: 46,
    gradeNumber: null,
    gradeCharacter: null,
    creditRegis: 3,
    studyYearInRegis: 4,
    studyTermInRegis: 1,
    semesterYearInRegis: 2568,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    regisId: 47,
    studentId: '6520501001',
    creditRequireId: 7,
    subjectCourseId: 47,
    gradeNumber: null,
    gradeCharacter: null,
    creditRegis: 3,
    studyYearInRegis: 4,
    studyTermInRegis: 1,
    semesterYearInRegis: 2568,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    regisId: 48,
    studentId: '6520501001',
    creditRequireId: 7,
    subjectCourseId: 48,
    gradeNumber: null,
    gradeCharacter: null,
    creditRegis: 3,
    studyYearInRegis: 4,
    studyTermInRegis: 1,
    semesterYearInRegis: 2568,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    regisId: 49,
    studentId: '6520501002',
    creditRequireId: 8,
    subjectCourseId: 1,
    gradeNumber: 1.5,
    gradeCharacter: 'D+',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    regisId: 50,
    studentId: '6520501002',
    creditRequireId: 9,
    subjectCourseId: 2,
    gradeNumber: 1,
    gradeCharacter: 'D',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    regisId: 51,
    studentId: '6520501002',
    creditRequireId: 8,
    subjectCourseId: 3,
    gradeNumber: 1.5,
    gradeCharacter: 'D+',
    creditRegis: 3,
    studyYearInRegis: 1,
    studyTermInRegis: 1,
    semesterYearInRegis: 2565,
    semesterPartInRegis: 'ภาคต้น',
    gradeLabelId: null,
  },
];

const factTermSummary: Prisma.FactTermSummaryCreateManyInput[] = [
  {
    TermSummaryId: 1,
    studentId: '6520501001',
    creditTerm: 18,
    creditAll: 18,
    gpa: 3.33,
    gpax: 3.33,
    studyYear: 1,
    studyTerm: 1,
    planStatus: 'ผ่าน',
    studentStatus: 'กำลังศึกษา',
    isCoop: false,
    generalSubjectCredit: 8,
    specificSubjectCredit: 10,
    freeSubjectCredit: 0,
    selectSubjectCredit: 0,
    generalSubjectCreditAll: 8,
    specificSubjectCreditAll: 10,
    freeSubjectCreditAll: 0,
    selectSubjectCreditAll: 0,
    semesterYearInTerm: 2565,
    semesterPartInTerm: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    TermSummaryId: 2,
    studentId: '6520501001',
    creditTerm: 19,
    creditAll: 37,
    gpa: 3.45,
    gpax: 3.39,
    studyYear: 1,
    studyTerm: 2,
    planStatus: 'ผ่าน',
    studentStatus: 'กำลังศึกษา',
    isCoop: false,
    generalSubjectCredit: 5,
    specificSubjectCredit: 14,
    freeSubjectCredit: 0,
    selectSubjectCredit: 0,
    generalSubjectCreditAll: 13,
    specificSubjectCreditAll: 24,
    freeSubjectCreditAll: 0,
    selectSubjectCreditAll: 0,
    semesterYearInTerm: 2565,
    semesterPartInTerm: 'ภาคปลาย',
    gradeLabelId: null,
  },
  {
    TermSummaryId: 3,
    studentId: '6520501001',
    creditTerm: 21,
    creditAll: 58,
    gpa: 3.31,
    gpax: 3.36,
    studyYear: 2,
    studyTerm: 1,
    planStatus: 'ผ่าน',
    studentStatus: 'กำลังศึกษา',
    isCoop: false,
    generalSubjectCredit: 4,
    specificSubjectCredit: 17,
    freeSubjectCredit: 0,
    selectSubjectCredit: 0,
    generalSubjectCreditAll: 17,
    specificSubjectCreditAll: 41,
    freeSubjectCreditAll: 0,
    selectSubjectCreditAll: 0,
    semesterYearInTerm: 2566,
    semesterPartInTerm: 'ภาคต้น',
    gradeLabelId: null,
  },
  {
    TermSummaryId: 4,
    studentId: '6520501001',
    creditTerm: 19,
    creditAll: 77,
    gpa: 3.61,
    gpax: 3.42,
    studyYear: 2,
    studyTerm: 2,
    planStatus: 'ผ่าน',
    studentStatus: 'กำลังศึกษา',
    isCoop: false,
    generalSubjectCredit: 4,
    specificSubjectCredit: 15,
    freeSubjectCredit: 0,
    selectSubjectCredit: 0,
    generalSubjectCreditAll: 21,
    specificSubjectCreditAll: 56,
    freeSubjectCreditAll: 0,
    selectSubjectCreditAll: 0,
    semesterYearInTerm: 2566,
    semesterPartInTerm: 'ภาคปลาย',
    gradeLabelId: null,
  },
  {
    TermSummaryId: 5,
    studentId: '6520501001',
    creditTerm: 18,
    creditAll: 95,
    gpa: 3.75,
    gpax: 3.48,
    studyYear: 3,
    studyTerm: 1,
    planStatus: 'ผ่าน',
    studentStatus: 'กำลังศึกษา',
    isCoop: false,
    generalSubjectCredit: 3,
    specificSubjectCredit: 15,
    freeSubjectCredit: 0,
    selectSubjectCredit: 0,
    generalSubjectCreditAll: 24,
    specificSubjectCreditAll: 71,
    freeSubjectCreditAll: 0,
    selectSubjectCreditAll: 0,
    semesterYearInTerm: 2566,
    semesterPartInTerm: 'ภาคต้น',
    gradeLabelId: null,
  },
];

async function clearDatabase() {
  console.log('Clearing existing data...');
  await prisma.factRegister.deleteMany();
  await prisma.factStdPlan.deleteMany();
  await prisma.factTermSummary.deleteMany();
  await prisma.subjectCredit.deleteMany();
  await prisma.subjectCourse.deleteMany();
  await prisma.subject.deleteMany();
  await prisma.creditRequire.deleteMany();
  await prisma.student.deleteMany();
  await prisma.studentStatus.deleteMany();
  await prisma.coursePlan.deleteMany();
  await prisma.course.deleteMany();
  await prisma.gradeLabel.deleteMany();
  await prisma.subjectCaterogy.deleteMany();
}

async function seedDatabase() {
  console.log('Seeding reference data...');
  await prisma.subjectCaterogy.createMany({ data: subjectCategories });
  await prisma.gradeLabel.createMany({ data: gradeLabels });
  await prisma.course.createMany({ data: courses });
  await prisma.coursePlan.createMany({ data: coursePlans });
  await prisma.subject.createMany({ data: subjects });
  await prisma.subjectCourse.createMany({ data: subjectCourses });
  await prisma.subjectCredit.createMany({ data: subjectCredits });
  await prisma.studentStatus.createMany({ data: studentStatuses });
  await prisma.student.createMany({ data: students });
  await prisma.creditRequire.createMany({ data: creditRequires });
  await prisma.factRegister.createMany({ data: factRegisters });
  await prisma.factTermSummary.createMany({ data: factTermSummary });
}

async function main() {
  await clearDatabase();
  await seedDatabase();
  console.log('Seeding finished.');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async e => {
    console.error('Seeding failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
